---
root: true
extends:
  - eslint:recommended
  - plugin:react-hooks/recommended
  - "@rocketseat/eslint-config/react"
plugins:
  - react-refresh
rules:
  react-refresh/only-export-components:
  - warn
  - allowConstantExport: true
  "@typescript-eslint/no-non-null-assertion": 'off'
